version: 2
jobs:
  build:
    working_directory: ~/npm-module-template
    docker:
      - image: circleci/node:8
    steps:
      - run:
          name: set-npm-registry-token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint-ci
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build
      - store_artifacts:
          path: coverage
          prefix: coverage
      - deploy:
          name: Deploy To NPM
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              npm publish .
            fi