version: 2
jobs:
  build:
    working_directory: ~/npm-module-template
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint-ci
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build
      - store_artifacts:
          path: coverage
          prefix: coverage
      - run:
          name: post-codecov
          command: codecov --token=$CODECOV_TOKEN
